"""
Plot estimation error of inferred signal in compressed sensing 
from error objects (.npz) generated by calculate_errors.py.

Created by Nirag Kadakia at 20:00 08-20-2017
This work is licensed under the 
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 
International License. 
To view a copy of this license, visit 
http://creativecommons.org/licenses/by-nc-sa/4.0/.
"""

import scipy as sp
import sys
sys.path.append('../src')
from utils import get_flag
from load_specs import read_specs_file
from save_data import save_figure
from load_data import load_errors
import matplotlib.pyplot as plt
from plot_formats import error_plots_formatting


def plot_errors(data_flag, axes_to_plot = [0, 1]):
	"""
	Plot estimation error of inferred signal in compressed sensing 
	from error objects (.npz) generated by calculate_errors.py.	
	"""
	
	data_flag = get_flag()
	
	list_dict = read_specs_file(data_flag)
	for key in list_dict:
		exec("%s = list_dict[key]" % key)
		
	assert max(axes_to_plot) < len(iter_vars.keys()), 'Error: Plot ' \
				'axes do not respect dimension of iterated ' \
				'variables of span %s.' % len(iter_vars.keys())
	iter_plot_var = iter_vars.keys()[axes_to_plot[0]]
	x_axis_var = iter_vars.keys()[axes_to_plot[1]]
	
	errors = load_errors(data_flag)
	
	fig = error_plots_formatting(x_axis_var)
	for idx, val in enumerate(iter_vars[iter_plot_var]):
		plt.plot(iter_vars[x_axis_var], errors[idx,:], linewidth = 0.5)
	save_figure(fig, 'errors', data_flag)
	plt.show()
	
if __name__ == '__main__':
	data_flag = get_flag()
	plot_errors(data_flag)